// COMPONENTS
export { default as Navbar } from '../components/Navbar'
export { default as Footer } from '../components/Footer'
export { default as GoTo } from '../components/GoTo'
export { default as Home } from '../components/pages/Home'
export { default as SonOfSenegal } from '../components/pages/SonOfSenegal'
export { default as TheLeader } from '../components/pages/TheLeader'
export { default as TheVisionary } from '../components/pages/TheVisionary'
export { default as ThePhilanthropist } from '../components/pages/ThePhilanthropist'
export { default as Projects } from '../components/pages/Projects'


export { default as SplitDiv } from '../components/SplitDiv'
export { default as TextLayout } from '../components/TextLayout'
export { default as Stat} from '../components/Stat'
export { default as Contact} from '../components/Contact'

export { default as Hero } from '../components/Hero'
export { default as Slide } from '../components/Slide'
export { default as ContributionsMap } from '../components/ContributionsMap'
export { default as ABSFacts } from '../components/pages/ABSFacts' 
export { default as MenuComponent } from '../components/Menu/MenuComponent'
export { default as Timeline} from '../components/Timeline'
export { default as TimelineElement } from '../components/TimelineElement'
export { default as AndTheCommunity } from '../components/AndTheCommunity'
export { default as Links } from '../components/Links'

export { default as ProjectCard } from '../components/Projects/ProjectCard'
export { default as Button } from '../components/Button'

export { default as NotFound } from '../components/NotFound'
export { default as Socials } from '../components/Socials'
export { default as ContactForm } from '../components/ContactForm'


// IMAGES

export { default as sudquotidien} from '../components/.images/press/sudQuotidienLogo.jpg'
export { default as directNews} from '../components/.images/press/directNews.jpg'
export { default as senego} from '../components/.images/press/senego.png'
export { default as seneweb} from '../components/.images/press/seneweb.png'

export { default as mapsenegal } from '../components/.images/map_senegal.jpg'
export { default as mapsenegaldark } from '../components/.images/map_senegal_dark.jpg'
export { default as mapafrica } from '../components/.images/mapafrica.jpg'
export { default as flagsenegal } from '../components/.images/flagsenegal.png'
export { default as flagsenegal2 } from '../components/.images/flagsenegal2.png'
export { default as senegalHero } from '../components/.images/senegalHero.jpg'
export { default as mausoleHero } from '../components/.images/mausoleHero.png'
export { default as c50 } from '../components/.images/c50.png'
export { default as daara } from '../components/.images/daara.jpg'
export { default as leket } from '../components/.images/leket.png'
export { default as leket2 } from '../components/.images/leket2_.jpg'
export { default as water } from '../components/.images/water.jpg'
export { default as workforce } from '../components/.images/workforce.jpg'
export { default as daara2 } from '../components/.images/daara.png'

export { default as abs_signature } from '../components/.branding/abs_signature.svg'

export { default as abssuit1 } from '../components/.photos/abs_suit_2.JPG'
export { default as abswhite } from '../components/.photos/abs_white_arms.PNG'
export { default as abssit } from '../components/.photos/abs_sit.png'
export { default as abssit2 } from '../components/.photos/abs_sit_.png'
export { default as abshero } from '../components/.photos/abs_blue_.jpg'
export { default as absleader } from '../components/.photos/abs_blue.JPG'
export { default as absstand } from '../components/.photos/abs_white_wall.jpg'
export { default as absyellowfit } from '../components/.photos/abs_yellow_fit.PNG'

export { default as fam1 } from '../components/.photos/family/fam1.jpg'
export { default as fam2 } from '../components/.photos/family/fam2.jpg'
export { default as fam3 } from '../components/.photos/family/fam3.jpg'
export { default as couple1 } from '../components/.photos/family/couple1.jpg'
export { default as couple2 } from '../components/.photos/family/couple2.jpg'
export { default as jumeaux } from '../components/.photos/family/jumeaux.jpg'
export { default as jumeaux_ } from '../components/.photos/family/jumeaux.png'